
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TheOnePercents.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Company
{

    public Company()
    {

        this.Competitions = new HashSet<Competition>();

        this.Memberships = new HashSet<Membership>();

        this.Tasks = new HashSet<Task>();

    }


    public System.Guid CompanyID { get; set; }

    public string CompanyName { get; set; }

    public Nullable<System.Guid> SettingID { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string CreateUser { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string UpdateUser { get; set; }



    public virtual ICollection<Competition> Competitions { get; set; }

    public virtual ICollection<Membership> Memberships { get; set; }

    public virtual ICollection<Task> Tasks { get; set; }

}

}
