
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TheOnePercents.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Membership
{

    public System.Guid MembershipID { get; set; }

    public System.Guid PrincipalUserID { get; set; }

    public System.Guid CompanyID { get; set; }

    public string Password { get; set; }

    public int PasswordFormat { get; set; }

    public string PasswordSalt { get; set; }

    public System.Guid PasswordSetIdentifier { get; set; }

    public string MobilePin { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string LoweredEmail { get; set; }

    public string PasswordQuestion { get; set; }

    public string PasswordAnswer { get; set; }

    public bool IsApproved { get; set; }

    public bool IsLockedOut { get; set; }

    public Nullable<bool> IsOnHold { get; set; }

    public Nullable<System.DateTime> LastLoginDate { get; set; }

    public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }

    public Nullable<System.DateTime> LastLockoutDate { get; set; }

    public Nullable<int> FailedPasswordAttemptCount { get; set; }

    public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }

    public Nullable<int> FailedPasswordAnswerAttemptCount { get; set; }

    public Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowStart { get; set; }

    public string Comment { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string CreateUser { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string UpdateUser { get; set; }



    public virtual Company Company { get; set; }

}

}
