
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TheOnePercents.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Task
{

    public Task()
    {

        this.UserTasks = new HashSet<UserTask>();

    }


    public int TaskID { get; set; }

    public System.Guid CompanyID { get; set; }

    public System.Guid CompetitionID { get; set; }

    public string TaskName { get; set; }

    public string TaskDescription { get; set; }

    public Nullable<int> TaskPoints { get; set; }

    public Nullable<bool> Active { get; set; }

    public string CreateUser { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string UpdateUser { get; set; }



    public virtual Company Company { get; set; }

    public virtual Competition Competition { get; set; }

    public virtual ICollection<UserTask> UserTasks { get; set; }

}

}
